services:
  db:
    image: postgres:16-alpine
    container_name: ckblog-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ckblog
      POSTGRES_USER: ckblog_user
      POSTGRES_PASSWORD: ckblog_secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ckblog-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ckblog.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pgdata:
